//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Herbarium
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class herbariumEntities : DbContext
    {
        public herbariumEntities()
            : base("name=herbariumEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<city> city { get; set; }
        public virtual DbSet<district> district { get; set; }
        public virtual DbSet<family> family { get; set; }
        public virtual DbSet<genus> genus { get; set; }
        public virtual DbSet<habitat> habitat { get; set; }
        public virtual DbSet<major> major { get; set; }
        public virtual DbSet<species> species { get; set; }
        public virtual DbSet<speciesdetails> speciesdetails { get; set; }
        public virtual DbSet<synonym> synonym { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<neighborhood> neighborhood { get; set; }
        public virtual DbSet<plant> plant { get; set; }
        public virtual DbSet<log> log { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<user_auths> user_auths { get; set; }
        public virtual DbSet<grid> grid { get; set; }
    }
}
