//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Herbarium
{
    using System;
    using System.Collections.Generic;

    public partial class plant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public plant()
        {
        }

        public int id { get; set; }
        public string herbno { get; set; }
        public Nullable<int> speciesid { get; set; }
        public Nullable<bool> issynonym { get; set; }
        public string localname { get; set; }
        public string subsp { get; set; }
        public string variety { get; set; }
        public Nullable<bool> endemism { get; set; }
        public string typeexample { get; set; }
        public Nullable<int> districtid { get; set; }
        public string localite { get; set; }
        public Nullable<int> habitat { get; set; }
        public Nullable<double> minimum { get; set; }
        public Nullable<double> maximum { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public byte[] photo { get; set; }
        public string collector { get; set; }
        public string diagnose { get; set; }
        public string explanation { get; set; }

        public virtual district district { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<grid> grid { get; set; }
    }
}
